# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Doguitos' do
  use_frameworks!

  # Pods for Doguitos
	pod 'Alamofire', '5.0.0-beta.3'
	pod 'RealmSwift', '3.15.0'
	pod 'SDWebImage', '4.4.1'
	pod 'IQKeyboardManagerSwift', '6.3.0'
	pod 'SVProgressHUD', '2.2.5'

  target 'DoguitosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoguitosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
